import "./globals.css";
import { LoadingProvider } from "@/lib/contexts/LoadingContext";
import { NextThemesProvider } from "@/lib/contexts/NextThemeProvider";
import { SessionProvider } from "@/lib/contexts/SessionContext";
import type { Session } from "@/lib/types";
import jwt from "jsonwebtoken";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { cookies } from "next/headers";
import { ViewTransitions } from "next-view-transitions";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900"
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900"
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookie = await cookies();
	const encryptedSession = cookie.get(`${process.env.SESSION}`)?.value;
	let session = null;
	let isExpired = false;
	if (encryptedSession) {
		try {
			session = jwt.verify(encryptedSession, `${process.env.SESSION_SECRET}`, {
				ignoreExpiration: true
			}) as Session;
		} catch (_) {
			session = null;
			isExpired = true;
		}
		if (session?.exp && session.exp < Date.now() / 1000) isExpired = true;
	}

	return (
		<ViewTransitions>
			<html lang="en" suppressHydrationWarning>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<SessionProvider session={session} isExpired={isExpired}>
						<NextThemesProvider>
							<NextTopLoader
								color="oklch(var(--primary-foreground))"
								showSpinner={false}
							/>
							<LoadingProvider>{children}</LoadingProvider>
						</NextThemesProvider>
						<Toaster closeButton richColors />
					</SessionProvider>
				</body>
			</html>
		</ViewTransitions>
	);
}
